# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonalBookkeeping' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for PersonalBookkeeping

  pod 'native-navigation', :path => '../node_modules/native-navigation'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      'RCTAnimation',
      'RCTImage',
      'RCTNetwork',
      'DevSupport',
      'ART'

        # Add any other subspecs you want to use in your project
      ]

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
